FROM mambaorg/micromamba:1.5.6
LABEL maintainer="Chun-Jie Liu <chunjie.sam.liu@gmail.com>"
# kallisto.salmon.cufflinks
COPY --chown=$MAMBA_USER:$MAMBA_USER env.yaml /tmp/env.yaml

ARG MAMBA_DOCKERFILE_ACTIVATE=1
ARG DEBIAN_FRONTEND=noninteractive

ARG MAMBA_USER=mambauser
ARG MAMBA_USER_ID=57439
ARG MAMBA_USER_GID=57439
ENV MAMBA_USER=$MAMBA_USER
ENV MAMBA_USER_ID=$MAMBA_USER_ID
ENV MAMBA_USER_GID=$MAMBA_USER_GID

USER root

RUN apt-get update \
  && apt-get install -y \
  ca-certificates \
  build-essential \
  zlib1g-dev \
  libhdf5-dev \
  wget \
  git  \
  cmake \
  curl \
  g++ \
  gfortran \
  libblas-dev \
  libgsl-dev \
  liblapack-dev \
  make \
  r-base \
  r-cran-nloptr \
  zlib1g-dev \
  libxml-libxml-perl \
  libcurl4-openssl-dev \
  libxml2-dev

RUN micromamba install -y -n base -f /tmp/env.yaml && \
  micromamba clean --all --yes


RUN pip install deeptools==3.2.0 \
  && pip install rmats2sashimiplot \
  && pip install Cython \
  && mkdir /rmats_build \
  && cd /rmats_build \
  && git clone https://github.com/Xinglab/rmats-turbo.git \
  && cd rmats-turbo \
  && echo '' > setup_environment.sh \
  && ./build_rmats \
  && mkdir /rmats \
  && cd /rmats \
  && cp /rmats_build/rmats-turbo/rmats.py ./ \
  && cp /rmats_build/rmats-turbo/cp_with_prefix.py ./ \
  && cp /rmats_build/rmats-turbo/*.so ./ \
  && mkdir rMATS_C \
  && cp /rmats_build/rmats-turbo/rMATS_C/rMATSexe ./rMATS_C \
  && mkdir rMATS_P \
  && cp /rmats_build/rmats-turbo/rMATS_P/*.py ./rMATS_P \
  && mkdir rMATS_R \
  && cp /rmats_build/rmats-turbo/rMATS_R/*.R ./rMATS_R \
  # Remove build dir
  && rm -rf /rmats_build \
  && chmod 777 /rmats/rmats.py \
  && cp -r /rmats/* /usr/local/bin

RUN git clone https://github.com/pachterlab/kallisto.git \
  && cd kallisto \
  && git checkout v0.50.0  \
  && mkdir build \
  && cd build \
  && cmake .. \
  && make \
  && make install


ENV PATH /sratoolkit/bin/:/rmats/:/opt/conda/bin/:$PATH

USER $MAMBA_USER
WORKDIR /rmats
ENTRYPOINT []
CMD []