
FROM debian:buster
LABEL maintainer="Chun-Jie Liu <chunjie.sam.liu@gmail.com>"

RUN apt-get update \
  && apt-get install -y \
  ca-certificates \
  cmake \
  curl \
  cython \
  g++ \
  gfortran \
  git \
  libblas-dev \
  libgsl-dev \
  liblapack-dev \
  make \
  python-dev \
  python-numpy \
  python-pip \
  r-base \
  r-cran-nloptr \
  zlib1g-dev \
  libxml-libxml-perl \
  pigz \
  fastqc \
  samtools \
  bedtools \
  trimmomatic \
  && rm -rf /var/lib/apt/lists/* \
  # Use a build dir to be removed after artifacts are extracted
  && pip install deeptools==3.2.0 \
  && mkdir /rmats_build \
  && cd /rmats_build \
  && git clone https://github.com/Xinglab/rmats-turbo.git \
  && cd rmats-turbo \
  && echo '' > setup_environment.sh \
  && ./build_rmats \
  && mkdir /rmats \
  && cd /rmats \
  && cp /rmats_build/rmats-turbo/rmats.py ./ \
  && cp /rmats_build/rmats-turbo/cp_with_prefix.py ./ \
  && cp /rmats_build/rmats-turbo/*.so ./ \
  && mkdir rMATS_C \
  && cp /rmats_build/rmats-turbo/rMATS_C/rMATSexe ./rMATS_C \
  && mkdir rMATS_P \
  && cp /rmats_build/rmats-turbo/rMATS_P/*.py ./rMATS_P \
  && mkdir rMATS_R \
  && cp /rmats_build/rmats-turbo/rMATS_R/*.R ./rMATS_R \
  # Remove build dir
  # && rm -rf /rmats_build \
  && chmod 777 /rmats/rmats.py \
  && echo 'export PATH=/rmats/:${PATH}' >> /etc/bash.bashrc \
  && cp -r /rmats/* /usr/local/bin \
  # Build STAR
  && mkdir /star_build \
  && cd /star_build \
  && curl -L -O https://github.com/alexdobin/STAR/archive/refs/tags/2.7.9a.tar.gz \
  && tar -zxvf 2.7.9a.tar.gz \
  && cd STAR-2.7.9a/source \
  && make STAR \
  && cp STAR /usr/local/bin \
  # Build sratoolkit
  && mkdir /sratoolkit_build \
  && cd /sratoolkit_build \
  && curl --output sratoolkit.tar.gz -L http://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz \
  && mkdir /sratoolkit \
  && tar -zxvf /sratoolkit_build/sratoolkit.tar.gz -C /sratoolkit --strip-components=1 \
  && rm -rf /sratoolkit_build \
  && echo 'export PATH=/sratoolkit/bin/:${PATH}' >> /etc/bash.bashrc \
  # && /sratoolkit/bin/vdb-config --restore-defaults \
  # Build Trimmomatic
  && mkdir /trimmomatic \
  && cd /trimmomatic \
  && curl --output trimmomatic.zip -L https://github.com/usadellab/Trimmomatic/files/5854859/Trimmomatic-0.39.zip \
  && unzip trimmomatic.zip \
  && rm trimmomatic.zip \
  && mkdir /opt/stringtie/ \
  && cd /opt/stringtie \
  && curl -O -L http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.3.Linux_x86_64.tar.gz \
  && tar -xzvf stringtie-1.3.3.Linux_x86_64.tar.gz \
  && ln -s /opt/stringtie/stringtie-1.3.3.Linux_x86_64/stringtie /usr/bin/stringtie \
  && rm stringtie-1.3.3.Linux_x86_64.tar.gz


ENV PATH /sratoolkit/bin/:/rmats/:$PATH
# Set defaults for running the image
WORKDIR /rmats
CMD ["python", "/rmats/rmats.py"]
# CMD ["--help"]

